/**
 * Shared dependency type re-export.
 * The actual bundle is generated by the Vite build; this file serves as an entry point for type safety.
 */
export type { SharedDependencyManifest } from '@esmap/shared';
